artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL : https://drive.google.com/file/d/1EsRM7ZK88kbwcFBr35IklJLLJAqaK01k/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation 
  unzip_data_dir: artifacts/data_ingestion/WineQuality.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/WineQuality.csv
  train: artifacts/data_transformation/train.csv
  test: artifacts/data_transformation/test.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts\data_transformation\train_arr.npy
  test_data_path: artifacts\data_transformation\test_arr.npy
  model_name: model.joblib